version: "3.8"

services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: sentinellog-dvwa
    restart: unless-stopped
    environment:
      - PHP_DISPLAY_ERRORS=On
    expose:
      - "80"

  lab-nginx:
    image: nginx:alpine
    container_name: sentinellog-lab-proxy
    restart: unless-stopped
    depends_on:
      - dvwa
    ports:
      - "8080:80"
    volumes:
      - ./lab/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/raw:/var/log/nginx
